services:
  app:
    image: node:18.16.0-alpine
    user: node
    working_dir: /home/node/app
    environment:
      API_DOCUMENT_DIR: ./docs/api
      DATABASE_URL: mysql://${DATABASE_USER}@db:3306/${DATABASE_NAME}?schema=public
      NODE_ENV: dev
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT:-3000}:3000
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
